---

- name: Configure Security on Windows
  hosts: windowshosts
  gather_facts: true
  
  tasks:
    - name: Open RDP Port
      win_firewall_rule:
        name: "Allow RDP"
        direction: in
        action: allow
        protocol: tcp
        local_port: 3389
        enabled: yes

    - name: Open SQL Server Port
      win_firewall_rule:
        name: "Allow SQL Server"
        direction: in
        action: allow
        protocol: tcp
        local_port: 1433
        enabled: yes

    - name: Turn on Real time protection in Windows Defender
      win_shell: |
        Set-MpPreference -DisableRealtimeMonitoring $false

  handlers:
    - name: Reboot if required
      win_reboot:
        reboot_timeout: 600
        post_reboot_delay: 30
      ignore_errors: true
