---

- name: Install Software on Windows
  hosts: windowshosts
  gather_facts: true
  
  tasks:
    - name: Install Google Chrome
      win_chocolatey:
        name: googlechrome
        state: present
        ignore_checksums: yes
      notify: Reboot if required

    - name: Install Mozilla Firefox
      win_chocolatey:
        name: firefox
        state: present
      notify: Reboot if required

    - name: Install Office 365
      win_chocolatey:
        name: office365business
        state: present
      notify: Reboot if required

    - name: Install VLC
      win_chocolatey:
        name: vlc
        state: present
      notify: Reboot if required

  handlers:
    - name: Reboot if required
      win_reboot:
        reboot_timeout: 600
        post_reboot_delay: 30
      ignore_errors: true
